/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ptcproyecto;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author 15-CW0001la
 */
public class Consultas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consultas
     */
    public Consultas() {
        initComponents();
        this.setPreferredSize(new Dimension(760,714));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPConsultas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BtnCerrar = new javax.swing.JButton();
        JPGestionConsultas = new javax.swing.JPanel();
        JBGuardarConsultas = new javax.swing.JButton();
        JBMostrarConsultas = new javax.swing.JButton();
        JBModificarConsultas = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPTablaDatosConsultas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPIngresoConsultas = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        JTFHoraCitas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rSDateChooser1 = new rojeru_san.componentes.RSDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(760, 655));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPConsultas.setBackground(new java.awt.Color(157, 34, 202));
        JPConsultas.setForeground(new java.awt.Color(153, 204, 255));
        JPConsultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Consultas");
        JPConsultas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1487086345-cross_81577.png"))); // NOI18N
        BtnCerrar.setToolTipText("");
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });
        JPConsultas.add(BtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 27, 25));

        getContentPane().add(JPConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 52));

        JPGestionConsultas.setBackground(new java.awt.Color(255, 255, 255));
        JPGestionConsultas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion de consultas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        JPGestionConsultas.setPreferredSize(new java.awt.Dimension(222, 330));
        JPGestionConsultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBGuardarConsultas.setBackground(new java.awt.Color(0, 136, 130));
        JBGuardarConsultas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JBGuardarConsultas.setForeground(new java.awt.Color(255, 255, 255));
        JBGuardarConsultas.setText("Guardar");
        JBGuardarConsultas.setPreferredSize(new java.awt.Dimension(90, 60));
        JBGuardarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGuardarConsultasActionPerformed(evt);
            }
        });
        JPGestionConsultas.add(JBGuardarConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 66, 190, 48));

        JBMostrarConsultas.setBackground(new java.awt.Color(0, 136, 130));
        JBMostrarConsultas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JBMostrarConsultas.setForeground(new java.awt.Color(255, 255, 255));
        JBMostrarConsultas.setText("Mostrar");
        JBMostrarConsultas.setPreferredSize(new java.awt.Dimension(90, 60));
        JBMostrarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMostrarConsultasActionPerformed(evt);
            }
        });
        JPGestionConsultas.add(JBMostrarConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 165, 190, 53));

        JBModificarConsultas.setBackground(new java.awt.Color(0, 136, 130));
        JBModificarConsultas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JBModificarConsultas.setForeground(new java.awt.Color(255, 255, 255));
        JBModificarConsultas.setText("Modificar");
        JBModificarConsultas.setPreferredSize(new java.awt.Dimension(90, 60));
        JPGestionConsultas.add(JBModificarConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 252, 190, -1));
        JPGestionConsultas.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 137, 210, 10));
        JPGestionConsultas.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 236, 210, 10));

        getContentPane().add(JPGestionConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 330));

        jPTablaDatosConsultas.setBackground(new java.awt.Color(255, 255, 255));
        jPTablaDatosConsultas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de las consultas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPTablaDatosConsultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPTablaDatosConsultas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 710, 160));

        getContentPane().add(jPTablaDatosConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 730, 210));

        jPIngresoConsultas.setBackground(new java.awt.Color(255, 255, 255));
        jPIngresoConsultas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de las consultas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPIngresoConsultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPIngresoConsultas.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 70, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Seleccione el tipo de cita:");
        jPIngresoConsultas.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        jPIngresoConsultas.add(JTFHoraCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 70, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Hora:");
        jPIngresoConsultas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        rSDateChooser1.setColorBackground(new java.awt.Color(0, 136, 130));
        jPIngresoConsultas.add(rSDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Fecha:");
        jPIngresoConsultas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        getContentPane().add(jPIngresoConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 500, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBGuardarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGuardarConsultasActionPerformed
        JOptionPane.showMessageDialog(null,"Datos ingresados correctamente");
    }//GEN-LAST:event_JBGuardarConsultasActionPerformed

    private void JBMostrarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMostrarConsultasActionPerformed

    }//GEN-LAST:event_JBMostrarConsultasActionPerformed

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        this.dispose ();
    }//GEN-LAST:event_BtnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JButton JBGuardarConsultas;
    private javax.swing.JButton JBModificarConsultas;
    private javax.swing.JButton JBMostrarConsultas;
    private javax.swing.JPanel JPConsultas;
    private javax.swing.JPanel JPGestionConsultas;
    private javax.swing.JTextField JTFHoraCitas;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPIngresoConsultas;
    private javax.swing.JPanel jPTablaDatosConsultas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private rojeru_san.componentes.RSDateChooser rSDateChooser1;
    // End of variables declaration//GEN-END:variables
}
